### ISSUE TITLE
define/override identifier already required

### ISSUE THREAD

**Issue by pmatos** [tonyg/racket-send-exp#3]
This is a pretty nifty idea but it doesn't seem to work. 
Try this:
```
#lang send-exp racket/base

(require racket/class)

(define (do-something obj)
  (define i {get-n obj})
  (define f (get-field n obj))

  (= i f))
```

You'll get:
```
 module: identifier already required in: define/override
```

This is in racket 7.1.

**Comment by tonyg** [comment]
Try `example.rkt`. It should work fine.

Your example will also work if you delete the `(require racket/class)` line. If you need it, as I'm sure you will if you're wanting this library in the first place :-) , try `(require (except-in racket/class define/override))`.
